### ISSUE TITLE
Better Cashier Client

### ISSUE THREAD

**Issue by jds691** [jds691/CI553-CW-miniStore#12]
## TODO

- [x] Select quantity of items ([JSpinner](https://docs.oracle.com/javase/tutorial/uiswing/components/spinner.html))
- [x] Remove items from list
- [x] Update number of items once added
