### ISSUE TITLE
Order Persistence

### ISSUE THREAD

**Issue by jds691** [jds691/CI553-CW-miniStore#6]
## Overview

Orders are not currently stored anywhere, only in memory. They should be stored and remembered between sessions in SQL.

## Tasks

- [x] Create a schema for Order in SQL
- [x] Intermediate table for linking Order and Product together
- [x] Make Order store a unique quantity for products
- [x] OrderProcessor loading Orders on init
- [x] OrderProcessor checking for updates in background
